### ISSUE TITLE
metrics server failure missed by tests

### ISSUE THREAD

**Issue by hyperbolic2346** [charmed-kubernetes/jenkins#302]
We had an issue crop up in 1.11 where the metrics server fails to connect. We need to verify this functionality in some way in our testing. In this specific case, kubelet stopped listening on the port metrics server is trying to reach. This was a known thing in 1.12+ and was fixed in those versions, but 1.11 did not have the fix and this behavior was changed in a point release.

**Comment by tvansteenburgh** [comment]
Issue moved to https://bugs.launchpad.net/bugs/1843315.
