### ISSUE TITLE
test_worker_master_removal does not leave cluster in state that it began

### ISSUE THREAD

**Issue by genet022** [charmed-kubernetes/jenkins#476]
When `validation.py::test_worker_master_removal` is run with only 1 master in your cluster, you will end up with 2 masters after the test completes. We need to add logic to maintain the state that the cluster began in.

**Comment by genet022** [comment]
If the test fails midway, you also potentially end up with a different number of units (masters/workers). We really just need to capture the number of masters/workers at the start, try the tests, then run a cleanup step regardless of pass/fail.

**Comment by Cynerva** [comment]
Thanks for raising the issue. I'm unassigning myself since I'm bogged down with other work, sorry.

**Comment by tvansteenburgh** [comment]
Issue moved to https://bugs.launchpad.net/bugs/1843320.
