### ISSUE TITLE
build-cdk-addons jobs destructively compete over calico images

### ISSUE THREAD

**Issue by Cynerva** [charmed-kubernetes/jenkins#498]
In both stable and edge charms, calico-node was failing to come up on calico units:
```
Sep 09 14:09:29 ip-172-30-0-132 charm-env[16857]: standard_init_linux.go:211: exec user process caused "exec format error"
Sep 09 14:09:30 ip-172-30-0-132 systemd[1]: calico-node.service: Main process exited, code=exited, status=1/FAILURE
```

This happened because an arm64 image got pushed to `rocks.canonical.com:443/cdk/calico/node:v3.6.1`, but the charms are configured to pull from there by default for all architectures.

`rocks.canonical.com:443/cdk/calico/kube-controllers:v3.6.1` is most likely impacted too.

Short-term, I've restored the amd64 image(s) by running build-release-cdk-addons-amd64-1.16, and @battlemidget has disabled the arm64, s390x, ppc64le jobs to prevent it from reverting back.

Long-term, we need to either get multiarch images on rocks.canonical.com, or add a workaround to the build-cdk-addons jobs to stop them from competing over the same images.

**Comment by tvansteenburgh** [comment]
Issue moved to https://bugs.launchpad.net/bugs/1843321.
